[package]
name = "vencode"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
sysinfo = "0.29" # (optional, for future CPU/mem display)
eframe = "0.27"
egui = "0.27"
scrap = "0.5.0"      # for screen capturing
